### ISSUE TITLE
Custom Commands in separate file

### ISSUE THREAD

**Issue by HeathNaylor** [go-jira/go-jira#259]
I attempted to create 2 files:

`~/.jira.d/config.yml`
`~/.jira.d/mine.yml`

`mine.yml` consisted of the following code:
```
custom-commands:
    - name: mine
      help: View issues currently assigned to yourself
      script: |
          jira list -a $JIRA_USER
```

**How to reproduce the problem:**
When typing `jira` I was not presented with the custom command `mine`. When I moved that same yaml into the `config.yml` and typed `jira`, I was able to see the custom command.

**Expected behavior:**
When creating a custom config file, I should be able to put one or more custom commands in and see them available when I type `jira` into the terminal.
